version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install Sphinx myst-parser sphinx-copybutton
      - pip install sphinxcontrib-apidoc sphinx-autoapi
      - pip install sphinxcontrib-programoutput furo


sphinx:
  configuration: docs/conf.py


